
def gen_init_strings(FILE, tot_attendants, tot_tables, tot_interests, exhibitors_idx, students_idx, static_ex, static_stud):

    strings = [
    '* this is an autogenerated file!',
    'SETS',
    'j           attendants          /j0*j%i/'%tot_attendants,
    'k           tables              /k0*k%i/'%tot_tables,
    'l           interests           /l0*l%i/'%tot_interests,
    'js(j)       subset of students  /j%i*j%i/'%(students_idx[0], students_idx[1]),
    'je(j)       subset of exhibit   /j%i*j%i/'%(exhibitors_idx[0], exhibitors_idx[1]),
    'js_s(js)    static students     /j%i*j%i/'%(static_stud[0], static_stud[1]),
    'je_s(je)    static exhibitors   /j%i*j%i/'%(static_ex[0], static_ex[1]),
    ';' ]

    for string in strings:
        #print(string)
        FILE.write('%s\n'%string)
    FILE.write('\n\n')


def gen_gams_table_2d(FILE):
    pass

def gen_gams_param(FILE):
    pass

def gen_gams_eqns(FILE, path_opt):
    '''
    '''
    with open(path_opt, 'r') as optFILE:
        opt_strings = optFILE.readlines()
    for string in opt_strings:
        FILE.write(string)
