# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0062_auto_20171012_1910'),
        ('exhibitors', '0064_auto_20171012_2200'),
    ]

    operations = [
    ]
